name: markdownlint ARM

on:
  push:
    branches: [ main, metrics ]
    paths:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: install markdownlint-cli
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
        arm64v8/ubuntu:latest \
        bash -exc 'apt-get update && apt-get -y install curl sudo && \
        curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && \
        sudo apt-get install -y nodejs && \
        sudo npm install -g markdownlint-cli'
    - name: run markdownlint
      run:  |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
        arm64v8/ubuntu:latest \
        bash -exc 'apt-get update && apt-get -y install curl sudo && \
        curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && \
        sudo apt-get install -y nodejs && \
        markdownlint .'
