name: sanitycheck ARM

on:
  push:
    branches: [ main, metrics ]
  pull_request:
    branches: [ main, metrics ]

jobs:
  misspell:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: install misspell
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
        arm64v8/ubuntu:latest \
        bash -exc 'apt-get update && apt-get -y install curl sudo && \
        curl -L -o ./install-misspell.sh https://git.io/misspell && \
        sudo ./install-misspell.sh'
    - name: run misspell
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
        arm64v8/ubuntu:latest \
        bash -exc 'apt-get update && apt-get -y install curl sudo && \
        sudo ./bin/misspell -error .'

  encoding:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: detect non-ASCII encoding and trailing space
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
        arm64v8/ubuntu:latest \
        bash -exc 'apt-get update && apt-get -y install curl sudo && \
        sudo apt install -y python3 && \
        uname -m && \
        python3 ./build/sanitycheck.py'
