name: sanitycheck ARM

on:
  push:
    branches: [ main, metrics ]
  pull_request:
    branches: [ main, metrics ]

jobs:
  misspell:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: install misspell
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
        arm64v8/ubuntu:latest \
        bash -exc 'apt-get update && apt-get -y install curl && \
        curl -L -o ./install-misspell.sh https://git.io/misspell && \
        sh ./install-misspell.sh'
    - name: run misspell
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
        arm64v8/ubuntu:latest \
        bash -exc 'apt-get update && apt-get -y install curl && \
        ./bin/misspell -error .'

  encoding:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: detect non-ASCII encoding and trailing space
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
        arm64v8/ubuntu:latest \
        bash -exc 'apt-get update && apt-get -y install curl && \
        apt install software-properties-common -y && \
        add-apt-repository ppa:deadsnakes/ppa -y && \
        apt install -y ${{ env.py }}-venv && \
        python3.7 -m venv .env && \
        source .env/bin/activate && \
        pip install --upgrade pip && \
        uname -m && \
        python3 ./build/sanitycheck.py'
